// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {openai} from '../models';

export function Chat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ConfigGet():Promise<entities.Config>;

export function ConfigSetApiKey(arg1:string):Promise<boolean>;

export function ConfigSetProxy(arg1:string):Promise<boolean>;

export function ConversationDelete(arg1:string):Promise<string>;

export function ConversationGetList():Promise<Array<entities.Conversation>>;

export function ConversationRename(arg1:string,arg2:string):Promise<string>;

export function MessageGetList(arg1:string,arg2:string):Promise<Array<openai.ChatCompletionMessage>>;

export function UtilCheckProxy(arg1:string,arg2:string):Promise<string>;

export function UtilMessageDialog(arg1:string,arg2:string,arg3:string):Promise<void>;
