// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1, arg2, arg3) {
  return window['go']['main']['App']['Chat'](arg1, arg2, arg3);
}

export function ConfigGet() {
  return window['go']['main']['App']['ConfigGet']();
}

export function ConfigSetApiKey(arg1) {
  return window['go']['main']['App']['ConfigSetApiKey'](arg1);
}

export function ConfigSetProxy(arg1) {
  return window['go']['main']['App']['ConfigSetProxy'](arg1);
}

export function ConversationDelete(arg1) {
  return window['go']['main']['App']['ConversationDelete'](arg1);
}

export function ConversationGetList() {
  return window['go']['main']['App']['ConversationGetList']();
}

export function ConversationRename(arg1, arg2) {
  return window['go']['main']['App']['ConversationRename'](arg1, arg2);
}

export function MessageGetList(arg1, arg2) {
  return window['go']['main']['App']['MessageGetList'](arg1, arg2);
}

export function UtilCheckProxy(arg1, arg2) {
  return window['go']['main']['App']['UtilCheckProxy'](arg1, arg2);
}

export function UtilMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['UtilMessageDialog'](arg1, arg2, arg3);
}
